source/accounts/urls.py
from django.urls import path
from accounts.views import logout_view, login_view, register_view, \
    user_activate_view, UserDetailView, UserChangeView, UserChangePasswordView, UsersListView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('activate/<token>/', user_activate_view, name='user_activate'),
    path('profile/<pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<pk>/edit', UserChangeView.as_view(), name='user_update'),
    path('profile/<pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password'),
    path('users/', UsersListView.as_view(), name='users_list'),
]


app_name = 'accounts'

source/main/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
]

source/accounts/models.py
from django.db import models
from uuid import uuid4


class Token(models.Model):
    token = models.UUIDField(verbose_name='token', default=uuid4)
    user = models.ForeignKey('auth.User', related_name='registration_tokens',
                             verbose_name='User', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.token)


class Git(models.Model):
    git = models.ForeignKey('auth.User', related_name='users_git', verbose_name='Git', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.git)

source/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=100, required=True, label='Username')
    first_name = forms.CharField(max_length=100, required=False, label='First name')
    last_name = forms.CharField(max_length=100, required=False, label='Last name')
    password = forms.CharField(max_length=100, required=True, widget=forms.PasswordInput,
                               label='Password')
    password_confirm = forms.CharField(max_length=100, required=True, widget=forms.PasswordInput,
                               label='Password confirm')
    email = forms.EmailField(required=True, label='Email')

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
            raise ValidationError('Username is already taken.', code='username_taken')
        except User.DoesNotExist:
            return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('This email is already registered', code='registered_email')
        except User.DoesNotExist:
            return email

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data.get('password')
        password_2 = self.cleaned_data.get('password_confirm')
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        if password_1 != password_2:
            raise ValidationError('Passwords do not match', code='password_do_not_match')
        if not (first_name or last_name):
            raise ValidationError('One of these First name or Last name fields should be filled')
        return self.cleaned_data


class UserChangeForm(forms.ModelForm):
    git = forms.CharField(label='Git profile')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'git']


class UserChangePasswordForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm']

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse
from main.settings import HOST_NAME
from django.views.generic import UpdateView, DetailView, ListView

from accounts.forms import SignUpForm, UserChangeForm, UserChangePasswordForm
from accounts.models import Token


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.GET.get('next', '')
            if next_url:
                return redirect(next_url)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'registration/login.html', context=context)


@login_required
def logout_view(request):
    logout(request)
    return redirect('webapp:index')


def register_view(request):
    if request.method == 'GET':
        form = SignUpForm()
        return render(request, 'register.html', context={'form': form})
    elif request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = User(
                 username=form.cleaned_data.get('username'),
                 first_name=form.cleaned_data.get('first_name'),
                 last_name=form.cleaned_data.get('last_name'),
                 email=form.cleaned_data.get('email'),
                 is_active=False
            )
            user.set_password(form.cleaned_data.get('password'))
            user.save()

            token = Token.objects.create(user=user)

            activation_url = HOST_NAME + reverse('accounts:user_activate', kwargs={'token': token})
            try:
                user.email_user(
                    'Вы зарегистрировались на сайте localhost:8000.',
                    'Для активации перейдите по ссылке: ' + activation_url
                )
            except ConnectionRefusedError:
                print('Could not send email. Server error.')

            return redirect('webapp:index')
        else:
            return render(request, 'register.html', context={'form': form})


def user_activate_view(request, token):
    token = get_object_or_404(Token, token=token)
    user = token.user
    user.is_active = True
    user.save()
    login(request, user)
    return redirect('webapp:index')


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    context_object_name = 'user_obj'
    form_class = UserChangeForm

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})


class UserChangePasswordView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_change_password.html'
    form_class = UserChangePasswordForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    # def form_valid(self, form):
    #     user = form.save()
    #     login(self.request, user)
    #     return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('accounts:login')


class UsersListView(ListView):
    template_name = 'registration/users.html'
    context_object_name = 'users'
    model = User
    paginate_by = 4
    paginate_orphans = 1

source/accounts/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <h1>Sign UP</h1>
    <form action="{% url 'accounts:register' %}" method="post" class="text-center">
        {% include 'partial/form.html' with button_text='Register' %}
    </form>
{% endblock %}

source/accounts/templates/user_change_password.html
{% extends 'base.html' %}
{% block title %}
    {{ user_obj.username }}
{% endblock %}

{% block menu %}
    {% if user_obj == request.user %}
    <li><a href="{% url 'accounts:user_detail' user_obj.pk %}">View</a></li>
    <li><a href="{% url 'accounts:user_update' user_obj.pk %}">Update profile</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Change password: <b>{{ user_obj.username }}</b></h1>
    <form action="{% url 'accounts:user_change_password' user_obj.pk %}" method="post">
        {% include 'partial/form.html' with button_text='Save' %}
    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ user_obj.username }}
{% endblock %}

{% block menu %}
    {% if user_obj == request.user %}
    <li><a href="{% url 'accounts:user_update' user_obj.pk %}">Edit</a></li>
    <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}">Change password</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Profile</h1>
    <p>Username: <b>{{ user_obj.username }}</b></p>
    <p>First name: <b>{{ user_obj.first_name }}</b></p>
    <p>Last name: <b>{{ user_obj.last_name }}</b></p>
    <p>Email: <b>{{ user_obj.email }}</b></p>
    <p>Git profile: <b>{{ user_obj.users_git }}</b></p>
{% endblock %}

source/accounts/templates/user_update.html
{% extends 'base.html' %}
{% block title %}
    {{ user_obj.username }}
{% endblock %}

{% block menu %}
    {% if user_obj == request.user %}
    <li><a href="{% url 'accounts:user_detail' user_obj.pk %}">View</a></li>
    <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}">Change password</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Edit Profile: <b>{{ user_obj.username }}</b></h1>
    <form action="{% url 'accounts:user_update' user_obj.pk %}" method="post">
        {% include 'partial/form.html' with button_text='Update' %}
    </form>
{% endblock %}