source/main/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
]

source/webapp/urls.py
from django.urls import path
from webapp.views import IndexView, TaskView, TaskCreateView, TaskUpdateView, \
    TaskDeleteView, StatusesView, StatusCreateView, StatusUpdateView, StatusDeleteView, TypesView, TypeCreateView, \
    TypeUpdateView, TypeDeleteView, ProjectsView, ProjectView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('task/<int:pk>/', TaskView.as_view(), name='task_view'),
    path('task/add/', TaskCreateView.as_view(), name='task_add'),
    path('task/<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('status/', StatusesView.as_view(), name='statuses_view'),
    path('status/add/', StatusCreateView.as_view(), name='status_add'),
    path('status/<int:pk>/update/', StatusUpdateView.as_view(), name='status_update'),
    path('status/<int:pk>/delete/', StatusDeleteView.as_view(), name='status_delete'),
    path('type/', TypesView.as_view(), name='types_view'),
    path('type/add/', TypeCreateView.as_view(), name='type_add'),
    path('type/<int:pk>/update/', TypeUpdateView.as_view(), name='type_update'),
    path('type/<int:pk>/delete/', TypeDeleteView.as_view(), name='type_delete'),
    path('projects/', ProjectsView.as_view(), name='projects_view'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project_view'),
    path('project/add/', ProjectCreateView.as_view(), name='project_add'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
]


app_name = 'webapp'

source/webapp/models.py
from django.db import models
PROJECT_STATUS = (
    ('active', 'active'),
    ('blocked', 'blocked'),
)


class Project(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Название проекта')
    description = models.CharField(max_length=500, null=True, blank=True, verbose_name='Описание')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    project_status = models.CharField(max_length=20, verbose_name='Статус проекта', choices=PROJECT_STATUS, default=PROJECT_STATUS[0][0])

    def __str__(self):
        return self.name


class Task(models.Model):
    summary = models.CharField(max_length=50, null=False, blank=False, verbose_name='краткое изложение')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='описание')
    status = models.ForeignKey('webapp.Status', related_name='task_status', on_delete=models.PROTECT, null=True, blank=True, verbose_name='статус')
    type = models.ForeignKey('webapp.Type', related_name='task_type', on_delete=models.PROTECT, null=True, blank=True, verbose_name='тип')
    project = models.ForeignKey('webapp.Project', related_name='projects_task', on_delete=models.PROTECT, null=True, blank=False, verbose_name='проект')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    def __str__(self):
        return self.summary


class Type(models.Model):
    type = models.CharField(max_length=50, verbose_name='тип')

    def __str__(self):
        return self.type


class Status(models.Model):
    status = models.CharField(max_length=50, verbose_name='статус')

    def __str__(self):
        return self.status

source/webapp/forms.py
from django import forms
from webapp.models import Status, Type, Task, Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'project_status']


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['summary', 'description', 'status', 'type', 'project']


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['status']


class TypeForm(forms.ModelForm):
    class Meta:
        model = Type
        fields = ['type']


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Search')

source/webapp/views/base_views.py
from django.views import View
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404, render, redirect


class ListView(TemplateView):
    context_key = 'objects'
    model = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.model.objects.all()
        return context


class DetailView(TemplateView):
    context_key = 'object'
    model = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = get_object_or_404(self.model, pk=kwargs['pk'])
        return context


# class UpdateView(View):
#     form_class = None
#     template_name = None
#     redirect_url = ''
#     model = None
#     pk_kwargs_url = 'pk'
#     context_object_name = None
#     object = None
#
#     def get(self, request, *args, **kwargs):
#         obj = self.get_object()
#         form = self.form_class(instance=obj)
#         return render(request, self.template_name, context={'form': form, self.context_object_name: obj})
#
#     def post(self, request, *args, **kwargs):
#         obj = self.get_object()
#         form = self.form_class(instance=obj, data=request.POST)
#         if form.is_valid():
#             return self.form_valid(form)
#         else:
#             return self.form_invalid(form)
#
#     def get_redirect_url(self):
#         return self.redirect_url
#
#     def form_valid(self, form):
#         self.object = self.get_object()
#         form.save()
#         return redirect(self.get_redirect_url())
#
#     def form_invalid(self, form):
#         return render(self.request, self.template_name, context={'form': form})
#
#     def get_object(self):
#         pk = self.kwargs.get(self.pk_kwargs_url)
#         obj = get_object_or_404(self.model, pk=pk)
#         return obj
#
#
class DeleteView(View):
    template_name = None
    redirect_url = ''
    model = None
    pk_kwargs_url = 'pk'
    context_object_name = None
    object = None
    error_page = None

    def get(self, request, *args, **kwargs):
        object = self.get_object()
        return render(request, self.template_name, context={self.context_object_name: object})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.project_status = 'blocked'
        self.object.save()
        return redirect(self.get_redirect_url())

    def get_object(self):
        pk = self.kwargs.get(self.pk_kwargs_url)
        obj = get_object_or_404(self.model, pk=pk)
        return obj

    def get_redirect_url(self):
        return self.redirect_url

source/webapp/views/project_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from django.views import View

from webapp.forms import ProjectForm, SimpleSearchForm
from webapp.models import Project
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView



class ProjectsView(ListView):
    template_name = 'project/list.html'
    context_object_name = 'projects'
    model = Project
    ordering = ['-created_at']
    paginate_by = 4
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(name__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class ProjectView(DetailView):
    template_name = 'project/project.html'
    context_object_name = 'project'
    model = Project


class ProjectCreateView(CreateView):
    model = Project
    template_name = 'project/create.html'
    form_class = ProjectForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})


class ProjectUpdateView(LoginRequiredMixin, UpdateView):
    model = Project
    template_name = 'project/update.html'
    form_class = ProjectForm
    context_object_name = 'project'

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})


class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    model = Project
    pk_kwargs_url = 'pk'
    template_name = 'project/delete.html'
    context_object_name = 'project'
    success_url = reverse_lazy('webapp:projects_view')


    # def dispatch(self, request, *args, **kwargs):
    #     return super().dispatch(request, *args, **kwargs)

    # def get(self, request, *args, **kwargs):
    #     project = self.get_object()
    #     return render(request, 'project/delete.html', context={'project': project})
    #
    # def post(self, request, *args, **kwargs):
    #     self.project = self.get_object()
    #     self.project.project_status = 'blocked'
    #     self.project.save()
    #     return redirect(self.get_redirect_url())
    #
    # def get_object(self):
    #     pk = self.kwargs.get(self.pk_kwargs_url)
    #     project = get_object_or_404(self.model, pk=pk)
    #     return project
    #
    # def get_redirect_url(self):
    #     return self.redirect_url

source/webapp/views/status_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from webapp.forms import StatusForm

from webapp.models import Status, Type
from django.views.generic import CreateView, UpdateView, DeleteView
from .base_views import ListView


class StatusesView(ListView):
    template_name = 'status/statuses.html'
    model = Status
    context_key = 'statuses'


class StatusCreateView(CreateView):
    model = Status
    template_name = 'status/create_status.html'
    form_class = StatusForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:statuses_view')


class StatusUpdateView(LoginRequiredMixin, UpdateView):
    model = Status
    template_name = 'status/status_update.html'
    form_class = StatusForm
    context_object_name = 'status'

    def get_success_url(self):
        return reverse('webapp:statuses_view')


class StatusDeleteView(LoginRequiredMixin, DeleteView):
    model = Status
    template_name = 'status/status_delete.html'
    context_object_name = 'status'
    pk_kwargs_url = 'pk'

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get(self.pk_kwargs_url)
        obj = get_object_or_404(self.model, pk=pk)
        return obj

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            return redirect('webapp:statuses_view')
        except:
            return render(request, 'error.html')

source/webapp/views/task_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode

from webapp.forms import TaskForm, SimpleSearchForm
from webapp.models import Task
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


class IndexView(ListView):
    template_name = 'task/index.html'
    context_object_name = 'tasks'
    model = Task
    ordering = ['-created_at']
    paginate_by = 4
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class TaskView(DetailView):
    template_name = 'task/task.html'
    context_object_name = 'task'
    model = Task


class TaskCreateView(CreateView):
    model = Task
    template_name = 'task/create.html'
    form_class = TaskForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:task_view', kwargs={'pk': self.object.pk})


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = 'task/update.html'
    form_class = TaskForm
    context_object_name = 'task'

    def get_success_url(self):
        return reverse('webapp:task_view', kwargs={'pk': self.object.pk})


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'task/delete.html'
    context_object_name = 'task'
    success_url = reverse_lazy('webapp:index')

source/webapp/views/type_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy

from webapp.forms import TypeForm

from webapp.models import Type
from django.views.generic import CreateView, UpdateView, DeleteView
from .base_views import ListView


class TypesView(ListView):
    template_name = 'type/types.html'
    model = Type
    context_key = 'types'


class TypeCreateView(CreateView):
    model = Type
    template_name = 'type/create_type.html'
    form_class = TypeForm

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:types_view')


class TypeUpdateView(LoginRequiredMixin, UpdateView):
    model = Type
    template_name = 'type/type_update.html'
    form_class = TypeForm
    context_object_name = 'type'

    def get_success_url(self):
        return reverse('webapp:types_view')


class TypeDeleteView(LoginRequiredMixin, DeleteView):
    model = Type
    template_name = 'type/type_delete.html'
    context_object_name = 'type'
    pk_kwargs_url = 'pk'

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get(self.pk_kwargs_url)
        obj = get_object_or_404(self.model, pk=pk)
        return obj

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            return redirect('webapp:types_view')
        except:
            return render(request, 'error_type.html')

source/webapp/templates/project/create.html
{% extends 'base.html' %}
{% block title %}Create project{% endblock %}
{% block menu %}
    <li><a href="{% url 'webapp:projects_view' %}">Projects</a></li>
{% endblock %}
{% block content %}
    <h1>Create project</h1>
    <form method="POST" action="{% url 'webapp:project_add' %}">
        {% include 'partial/project_form.html' with button_text="Create" %}
    </form>
{% endblock %}

source/webapp/templates/project/delete.html
{% extends "base.html" %}
{% block title %}Delete project{% endblock %}
{% block content %}
    <h1>Are you sure want to delete project "{{ project }}"?</h1>
    <form method="POST" action="{% url "webapp:project_delete" project.pk %}" class="text-center" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Confirm" class="btn btn-danger"></p>
        <p><a href="{% url 'webapp:projects_view' %}" class="btn btn-default">Cancel</a></p>
    </form>
{% endblock %}

source/webapp/templates/project/list.html
{% extends 'base.html' %}
{% block menu %}
    <li><a href="{% url 'webapp:project_add' %}">Add project</a></li>
    <li><a href="{% url 'webapp:index' %}">Tasks</a></li>
{% endblock %}
{% block content %}
    <h1 class="mt-3">Projects</h1>
    {% include 'partial/simple_search.html' %}
    <hr>
        {% if is_paginated  %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    <hr/>
    <div class="row">
        {% for project in projects %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mt-3">
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'webapp:project_view' project.pk %}"><h2 class="card-text card-link">
                            {{ project.name }}
                        </h2></a>
                        <a href="{% url 'webapp:project_update' project.pk %}"><i class="fas fa-edit"></i></a>
                        <a href="{% url 'webapp:project_delete' project.pk %}"><i class="fas fa-trash"></i></a>
                        <p class="card-text">{{ project.get_category_display }}</p>
                        <p class="card-text text-right"><b>Description: </b>{{ project.description }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
          {% if is_paginated  %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/project/project.html
{% extends 'base.html' %}
{% block title %}{{ project.name }}{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:project_update' project.pk %}">Edit</a></li>
    <li><a href="{% url 'webapp:project_delete' project.pk %}">Delete</a></li>
    <li><a href="{% url 'webapp:project_add' %}">Create</a></li>
{% endblock %}

{% block content %}
    <h1>{{ project.name }}</h1>
    <div class="pre"><p><b>Description: </b>{{ project.description }}</p></div>
    <p><b>Status: </b>{{ project.project_status }}</p>
    <p><b>Created at: </b>{{ project.created_at|date:'d.m.Y H:i:s' }}</p>
     <p><b>Updated at: </b> {{ project.updated_at|date:'d.m.Y H:i:s' }}</p>
    <hr/>
    <h3>Tasks</h3>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    <div class="task-list">
        {% for task in project.projects_task.all %}
            <hr>
            <div class="task">
                <p>{{ task.summary }} created at {{ task.created_at|date:'d.m.Y H:i:s' }}</p>
                <div class="pre">{{ task.description }}</div>
                <a href="{% url 'webapp:task_update' task.pk %}"><i class="fas fa-edit"></i></a>
                <a href="{% url 'webapp:task_delete' task.pk %}"><i class="fas fa-trash"></i></a>
                <a href="{% url 'webapp:task_add' %}"><i class="fas fa-plus-square"></i></a>
            </div>
            <hr>
        {% empty %}
            <p>No tasks yet.</p>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/project/update.html
{% extends "base.html" %}
{% block title %}Update project{% endblock %}
{% block menu %}
    <li><a href="{% url 'webapp:projects_view' %}">Projects</a></li>
{% endblock %}
{% block content %}
    <h1>Update Project</h1>
    <form method="POST" action="{% url "webapp:project_update" project.pk %}">
        {% include 'partial/project_form.html' with button_text="Update" %}
    </form>
{% endblock %}